name: chorus-detection
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - pip:
      - librosa==0.10.1
      - matplotlib==3.7.2
      - numpy==1.24.4
      - pandas==2.0.3
      - pydub==0.25.1
      - pytube==15.0.0
      - scikit-learn==1.3.0
      - tensorflow==2.10.0
